### PR TITLE
fix: add dashboard alert for security rules in api explorer

### LINKED ISSUE #718: Make a note in dashboard that security rules don't apply locally

### PR DESCRIPTION
**Pull request by davemooreuws**
also adds security definition to exported spec

closes #718

### CODE REVIEW

File: pkg/dashboard/frontend/src/components/apis/APIExplorer.tsx [hunk 1]
```diff
@@ -486,8 +488,25 @@ const APIExplorer = () => {
...
+                      <div className="flex-shrink-0">
+                        <InformationCircleIcon
+                          className="h-5 w-5"
+                          aria-hidden="true"
+                        />
+                      </div>
+                      <div className="ml-3 flex-1 md:flex md:justify-between">
+                        <p className="text-sm">
+                          Security rules are currently not enforced when using
+                          nitric for local development.
```
Comment (HomelessDinosaur) [inline pkg/dashboard/frontend/src/components/apis/APIExplorer.tsx]:
```suggestion
                          Nitric for local development.
```

File: pkg/dashboard/frontend/src/components/apis/APIExplorer.tsx [hunk 2]
```diff
@@ -486,8 +488,25 @@ const APIExplorer = () => {
                     </Button>
                   </div>
                 </div>
+                {selectedApiEndpoint.doc.components?.securitySchemes && (
+                  <Alert>
```
Comment (HomelessDinosaur) [inline pkg/dashboard/frontend/src/components/apis/APIExplorer.tsx]: Can the alert by a warning yellow? the white is difficult to see.

**Review by HomelessDinosaur — DISMISSED** [review]

File: cmd/stack.go [hunk 3]
```diff
@@ -223,13 +223,7 @@ var stackUpdateCmd = &cobra.Command{
...
 		tui.CheckErr(err)
 
-		additionalEnvFiles := []string{}
-
-		if envFile != "" {
-			additionalEnvFiles = append(additionalEnvFiles, envFile)
-		}
-
-		envVariables, err := env.ReadLocalEnv(additionalEnvFiles...)
+		envVariables, err := env.ReadLocalEnv()
```
Comment (tjholm) [inline cmd/stack.go]: disabling the --env-file args?

**Review by tjholm — DISMISSED** [review]

**Review by HomelessDinosaur — APPROVED** [review]

**Review by jyecusch — APPROVED** [review]
