### PR TITLE
fix(aws): don't create duplicate policies

### LINKED ISSUE #418: AWS: Duplicate policy creation causes conflicts
When creating the same resource with multiple policies, if policies have identical permissions and an identical principal this will lead to conflicts in policy creation under pulumi.

Screenshot_2022-12-03_at_13 14 48

### PR DESCRIPTION
**Pull request by asalkeld**
Note: I don't know the exact use case that caused this.. 

closes #418

### CODE REVIEW

File: pkg/provider/pulumi/aws/aws.go [hunk 1]
```diff
@@ -475,6 +477,14 @@ func (a *awsProvider) Deploy(ctx *pulumi.Context) error {
 			return err
 		}
 
+		_, ok := uniquePolicies[policyName]
+		if ok {
+			// no point creating multiple policies with the same content.
```
Comment (jyecusch) [inline pkg/provider/pulumi/aws/aws.go:482]: We should probably find out what caused this, it could be a mistake in the project that we could highlight as well as adding this protection.

**Review by jyecusch — APPROVED** [review]

**Review by tjholm — APPROVED** [review]

File: pkg/provider/pulumi/aws/aws.go (hunk 1 above)
Comment (tjholm) [reply pkg/provider/pulumi/aws/aws.go:482]: I think logging an error would be good if we can highlight this as part of our output logging during deployment.

Comment (asalkeld) [reply pkg/provider/pulumi/aws/aws.go:482]: mmm, let's get this merged and i'll try and do that..
