### PR TITLE
fix: add a link to installation instructions to setup docker

### LINKED ISSUE #364: Docker not running/installed error message.
The error message for when docker is not present or detected is currently - 

return nil, errors.New("neither podman nor docker found")

Provide a URL for help and a more helpful error message.

### PR DESCRIPTION
**Pull request by raksiv**

### CODE REVIEW

File: pkg/containerengine/docker.go [hunk 1]
```diff
@@ -64,7 +64,7 @@ func newDocker() (ContainerEngine, error) {
 
 	err = cmd.Run()
 	if err != nil {
-		fmt.Println("docker daemon not running, please start it..")
+		fmt.Println("\ndocker daemon not running, please start it.")
```
Comment (asalkeld) [inline pkg/containerengine/docker.go]: maybe just remove this line

Comment (raksiv) [reply pkg/containerengine/docker.go]: done :)

**Review by asalkeld — APPROVED** [review]

**Review by asalkeld — APPROVED** [review]
