### PR TITLE
feat: Catch panics and print a issue link for users to report bugs

### LINKED ISSUE #146: Catch and prompt to report unexpected errors
If someone encounters an unexpected error in the CLI, it would be nice if we could automate or streamline the process to report it to us so we can fix it. Let's look into top-level handling of unexpected errors, print any useful detail from the error and prompt the user to report it.

GitHub provides query params that could help us prefill an issue template, e.g. https://github.com/nitrictech/cli/issues/new?title=foo&body=bar

This shouldn't be done without the CLI user's permission, so let's prompt to report the bug, then open a URL and prefill what we can.

### PR DESCRIPTION
**Pull request by asalkeld**
When any command panics, catch the error and print a URL that the user can use to create a github bug issue.

Here is an example:

nitric list
  ERROR   An unexpected error occurred, please create a github issue by clicking on the link below
https://github.com/nitrictech/cli/issues/new?body=diagnostics%3A%0A++os%3A+linux%0A++arch%3A+amd64%0A++goversion%3A+go1.17.7%0A++cliversion%3A+v1.1.0-develop.14-42-g48aacf42a53389ae62b48616ecdf7864acb451c2-dirty%0Acommand%3A+nitric+stack+list%0Aerror%3A+%27runtime+error%3A+invalid+memory+address+or+nil+pointer+dereference%27%0Astacktrace%3A+%22goroutine+1+%5Brunning%5D%3A%5Cnruntime%2Fdebug.Stack%28%29%5Cn%5Ct%2Fhome%2Fangus%2F.gvm%2Fgos%2Fgo1.17.7%2Fsrc%2Fruntime%2Fdebug%2Fstack.go%3A24%0A++%2B0x65%5Cngithub.com%2Fnitrictech%2Fcli%2Fpkg%2Fghissue.BugLink%28%7B0x21e8d80%2C+0x4e12640%7D%29%5Cn%5Ct%2Fhome%2Fangus%2Fcode%2Fgo%2Fsrc%2Fgithub.com%2Fnitrictech%2Fcli%2Fpkg%2Fghissue%2Fbuglink.go%3A57%0A++%2B0x79%5Cnmain.Execute.func1%28%29%5Cn%5Ct%2Fhome%2Fangus%2Fcode%2Fgo%2Fsrc%2Fgithub.com%2Fnitrictech%2Fcli%2Fpkg%2Fcmd%2Froot.go%3A72%0A++%2B0x7e%5Cnpanic%28%7B0x21e8d80%2C+0x4e12640%7D%29%5Cn%5Ct%2Fhome%2Fangus%2F.gvm%2Fgos%2Fgo1.17.7%2Fsrc%2Fruntime%2Fpanic.go%3A1038%0A++%2B0x215%5Cngithub.com%2Fnitrictech%2Fcli%2Fpkg%2Fcmd%2Fstack.glob..func4%280x4e2a760%2C+%7B0x4e77260%2C%0A++0x0%2C+0x0%7D%29%5Cn%5Ct%2Fhome%2Fangus%2Fcode%2Fgo%2Fsrc%2Fgithub.com%2Fnitrictech%2Fcli%2Fpkg%2Fcmd%2Fstack%2Froot.go%3A189%0A++%2B0x28%5Cngithub.com%2Fspf13%2Fcobra.%28%2ACommand%29.execute%280x4e2a760%2C+%7B0x4e77260%2C+0x0%2C+0x0%7D%29%5Cn%5Ct%2Fhome%2Fangus%2F.gvm%2Fpkgsets%2Fgo1.17.7%2Fglobal%2Fpkg%2Fmod%2Fgithub.com%2Fspf13%2Fcobra%40v1.3.0%2Fcommand.go%3A860%0A++%2B0x5f8%5Cngithub.com%2Fspf13%2Fcobra.%28%2ACommand%29.ExecuteC%280x4e2ac60%29%5Cn%5Ct%2Fhome%2Fangus%2F.gvm%2Fpkgsets%2Fgo1.17.7%2Fglobal%2Fpkg%2Fmod%2Fgithub.com%2Fspf13%2Fcobra%40v1.3.0%2Fcommand.go%3A974%0A++%2B0x3bc%5Cngithub.com%2Fspf13%2Fcobra.%28%2ACommand%29.Execute%28...%29%5Cn%5Ct%2Fhome%2Fangus%2F.gvm%2Fpkgsets%2Fgo1.17.7%2Fglobal%2Fpkg%2Fmod%2Fgithub.com%2Fspf13%2Fcobra%40v1.3.0%2Fcommand.go%3A902%5Cnmain.addAlias.func1%280x4e77260%2C%0A++%7B0x4e77260%2C+0x0%2C+0x4%7D%29%5Cn%5Ct%2Fhome%2Fangus%2Fcode%2Fgo%2Fsrc%2Fgithub.com%2Fnitrictech%2Fcli%2Fpkg%2Fcmd%2Froot.go%3A112%0A++%2B0x232%5Cngithub.com%2Fspf13%2Fcobra.%28%2ACommand%29.execute%280xc00012b900%2C+%7B0x4e77260%2C+0x0%2C%0A++0x0%7D%29%5Cn%5Ct%2Fhome%2Fangus%2F.gvm%2Fpkgsets%2Fgo1.17.7%2Fglobal%2Fpkg%2Fmod%2Fgithub.com%2Fspf13%2Fcobra%40v1.3.0%2Fcommand.go%3A860%0A++%2B0x5f8%5Cngithub.com%2Fspf13%2Fcobra.%28%2ACommand%29.ExecuteC%280x4e2ac60%29%5Cn%5Ct%2Fhome%2Fangus%2F.gvm%2Fpkgsets%2Fgo1.17.7%2Fglobal%2Fpkg%2Fmod%2Fgithub.com%2Fspf13%2Fcobra%40v1.3.0%2Fcommand.go%3A974%0A++%2B0x3bc%5Cngithub.com%2Fspf13%2Fcobra.%28%2ACommand%29.Execute%28...%29%5Cn%5Ct%2Fhome%2Fangus%2F.gvm%2Fpkgsets%2Fgo1.17.7%2Fglobal%2Fpkg%2Fmod%2Fgithub.com%2Fspf13%2Fcobra%40v1.3.0%2Fcommand.go%3A902%5Cnmain.Execute%28%29%5Cn%5Ct%2Fhome%2Fangus%2Fcode%2Fgo%2Fsrc%2Fgithub.com%2Fnitrictech%2Fcli%2Fpkg%2Fcmd%2Froot.go%3A76%0A++%2B0x45%5Cnmain.main%28%29%5Cn%5Ct%2Fhome%2Fangus%2Fcode%2Fgo%2Fsrc%2Fgithub.com%2Fnitrictech%2Fcli%2Fpkg%2Fcmd%2Fmain.go%3A20%0A++%2B0x17%5Cn%22%0A&title=Command+%27nitric+stack+list%27+paniced%3A+runtime+error%3A+invalid+memory+address+or+nil+point

closes #146

### CODE REVIEW

File: pkg/ghissue/buglink.go [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+
+func BugLink(err interface{}) string {
+	issue := GHIssue{
+		Diagnostics: diag,
+		Error:       fmt.Sprint(err),
+		StackTrace:  string(debug.Stack()),
+		Command:     strings.Join(os.Args, " "),
+	}
+
+	title := "Command '" + issue.Command + "' paniced: " + utils.StringTrunc(issue.Error, 50)
```
Comment (HomelessDinosaur) [inline pkg/ghissue/buglink.go]: paniced -> panicked

**Review by HomelessDinosaur — CHANGES_REQUESTED** [review]

**Review by HomelessDinosaur — APPROVED** [review]
